[workspace]
members = ["core"]

[package]
name = "plap"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["loichyan <loichyan@foxmail.com>"]
edition = "2021"
rust-version = "1.56"

description = "An argument parser for proc-macros."
readme = "README.md"
repository = "https://github.com/loichyan/plap"

[dependencies]
plap-core = { path = "core" }

[dev-dependencies]
thiserror = "1.0"
trybuild = "1.0"
